import os
import re

app_js_path = r"d:\Projects\portfolio-beingAnujChaudhary\projects\anujsNotes\app.js"

new_decks = """const DECKS = {
    ep1: [
        { front: 'I', back: 'ich', hint: '1st person singular' },
        { front: 'You (informal)', back: 'du', hint: '2nd person singular' },
        { front: 'He', back: 'er', hint: '3rd person singular (male)' },
        { front: 'She', back: 'sie', hint: '3rd person singular (female)' },
        { front: 'It', back: 'es', hint: '3rd person singular (neuter)' },
        { front: 'We', back: 'wir', hint: '1st person plural' },
        { front: 'You all (plural)', back: 'ihr', hint: '2nd person plural' },
        { front: 'They', back: 'sie', hint: '3rd person plural' },
        { front: 'You (formal)', back: 'Sie', hint: 'Always capitalized' },
        { front: 'I learn', back: 'ich lerne', hint: 'lernen' },
        { front: 'You learn (informal)', back: 'du lernst', hint: 'lernen' },
        { front: 'He learns', back: 'er lernt', hint: 'lernen' },
        { front: 'She learns', back: 'sie lernt', hint: 'lernen' },
        { front: 'It learns', back: 'es lernt', hint: 'lernen' },
        { front: 'We learn', back: 'wir lernen', hint: 'lernen' },
        { front: 'You all learn', back: 'ihr lernt', hint: 'lernen' },
        { front: 'They learn', back: 'sie lernen', hint: 'lernen' },
        { front: 'You learn (formal)', back: 'Sie lernen', hint: 'lernen' },
        { front: 'I play', back: 'ich spiele', hint: 'spielen' },
        { front: 'You play', back: 'du spielst', hint: 'spielen' },
        { front: 'He plays', back: 'er spielt', hint: 'spielen' },
        { front: 'We play', back: 'wir spielen', hint: 'spielen' },
        { front: 'You all play', back: 'ihr spielt', hint: 'spielen' },
        { front: 'They play', back: 'sie spielen', hint: 'spielen' },
        { front: 'I live (reside)', back: 'ich wohne', hint: 'wohnen' },
        { front: 'You live', back: 'du wohnst', hint: 'wohnen' },
        { front: 'She lives', back: 'sie wohnt', hint: 'wohnen' },
        { front: 'We live', back: 'wir wohnen', hint: 'wohnen' },
        { front: 'You all live', back: 'ihr wohnt', hint: 'wohnen' },
        { front: 'They live', back: 'sie wohnen', hint: 'wohnen' },
        { front: 'I do/make', back: 'ich mache', hint: 'machen' },
        { front: 'You do', back: 'du machst', hint: 'machen' },
        { front: 'He does', back: 'er macht', hint: 'machen' },
        { front: 'We do', back: 'wir machen', hint: 'machen' },
        { front: 'You all do', back: 'ihr macht', hint: 'machen' },
        { front: 'They do', back: 'sie machen', hint: 'machen' },
        { front: 'I go', back: 'ich gehe', hint: 'gehen' },
        { front: 'You go', back: 'du gehst', hint: 'gehen' },
        { front: 'She goes', back: 'sie geht', hint: 'gehen' },
        { front: 'We go', back: 'wir gehen', hint: 'gehen' },
        { front: 'You all go', back: 'ihr geht', hint: 'gehen' },
        { front: 'They go', back: 'sie gehen', hint: 'gehen' },
        { front: 'I come', back: 'ich komme', hint: 'kommen' },
        { front: 'You come', back: 'du kommst', hint: 'kommen' },
        { front: 'He comes', back: 'er kommt', hint: 'kommen' },
        { front: 'We come', back: 'wir kommen', hint: 'kommen' },
        { front: 'You all come', back: 'ihr kommt', hint: 'kommen' },
        { front: 'They come', back: 'sie kommen', hint: 'kommen' },
        { front: 'I drink', back: 'ich trinke', hint: 'trinken' },
        { front: 'You drink', back: 'du trinkst', hint: 'trinken' },
        { front: 'We drink', back: 'wir trinken', hint: 'trinken' }
    ],
    ep2: [
        { front: 'W sounds like...', back: 'v', hint: 'Like in "Wasser" or "wir"' },
        { front: 'V sounds like...', back: 'f (usually)', hint: 'Like in "Vater" or "Vogel"' },
        { front: 'J sounds like...', back: 'y', hint: 'Like in "ja" or "Jahr"' },
        { front: 'Z sounds like...', back: 'ts', hint: 'Like in "zehn" or "Zeit"' },
        { front: 'S (at start of word) sounds like...', back: 'z', hint: 'Like in "Sonne" or "singen"' },
        { front: 'S (at end of word) sounds like...', back: 's', hint: 'Like in "Haus" or "Maus"' },
        { front: 'ß (Eszett) sounds like...', back: 'ss', hint: 'Like in "heißen" or "Fuß"' },
        { front: 'ei sounds like...', back: '"eye"', hint: 'Like in "mein", "dein", "nein"' },
        { front: 'ie sounds like...', back: 'long "ee"', hint: 'Like in "Liebe", "sie", "wie"' },
        { front: 'eu sounds like...', back: '"oy"', hint: 'Like in "neu", "Europa", "Euro"' },
        { front: 'äu sounds like...', back: '"oy"', hint: 'Like in "Häuser", "Mäuse"' },
        { front: 'au sounds like...', back: '"ow"', hint: 'Like in "Haus", "Maus", "blau"' },
        { front: 'ä (A-Umlaut) sounds like...', back: 'eh (like in "bed")', hint: 'Like in "Käse", "Mädchen"' },
        { front: 'ö (O-Umlaut) sounds like...', back: 'er (without the r)', hint: 'Make "ee" sound with round lips. Like "schön"' },
        { front: 'ü (U-Umlaut) sounds like...', back: 'ew', hint: 'Make "ee" sound with tight round lips. Like "fünf"' },
        { front: 'ch (after a, o, u, au) sounds like...', back: 'hard throat sound (loch)', hint: 'Like in "Buch", "auch", "machen"' },
        { front: 'ch (after e, i, ä, ö, ü, eu, äu) sounds like...', back: 'soft hissing sound (huge)', hint: 'Like in "ich", "mich", "dich"' },
        { front: 'sch sounds like...', back: 'sh', hint: 'Like in "Schule", "schön", "schlafen"' },
        { front: 'st (at start of word/syllable) sounds like...', back: 'sht', hint: 'Like in "Stadt", "stehen"' },
        { front: 'sp (at start of word/syllable) sounds like...', back: 'shp', hint: 'Like in "spielen", "Sport"' },
        { front: 'tion (at end of word) sounds like...', back: 'tsi-ohn', hint: 'Like in "Information", "Station"' },
        { front: 'ig (at end of word) sounds like...', back: 'ikh', hint: 'Like in "zwanzig", "richtig"' },
        { front: 'R (at start of word) sounds like...', back: 'guttural trill (from throat)', hint: 'Like in "rot", "Reise"' },
        { front: 'R (at end of word) sounds like...', back: 'vocalized (like short "a")', hint: 'Like in "Vater", "Bruder", "wir"' },
        { front: 'A sounds like...', back: 'ah', hint: 'Like in "Apfel", "Mann"' },
        { front: 'E sounds like...', back: 'eh', hint: 'Like in "Elefant", "essen"' },
        { front: 'I sounds like...', back: 'ee', hint: 'Like in "Igel", "Insel"' },
        { front: 'O sounds like...', back: 'oh', hint: 'Like in "Opa", "oft"' },
        { front: 'U sounds like...', back: 'oo', hint: 'Like in "Uhr", "und"' },
        { front: 'B (at end of word) sounds like...', back: 'p', hint: 'Like in "gelb", "Dieb"' },
        { front: 'D (at end of word) sounds like...', back: 't', hint: 'Like in "Hund", "Bad"' },
        { front: 'G (at end of word) sounds like...', back: 'k', hint: 'Like in "Tag", "Zug"' },
        { front: 'Qu sounds like...', back: 'kv', hint: 'Like in "Qualität", "Quatsch"' },
        { front: 'Ph sounds like...', back: 'f', hint: 'Like in "Physik", "Foto"' },
        { front: 'Th sounds like...', back: 't (no "th" sound in German)', hint: 'Like in "Theater", "Thema"' },
        { front: 'C (before a, o, u) sounds like...', back: 'k', hint: 'Like in "Computer", "Café"' },
        { front: 'C (before e, i, ä, ö) sounds like...', back: 'ts', hint: 'Like in "Cent", "circa"' },
        { front: 'Y (in middle of word) sounds like...', back: 'ü', hint: 'Like in "Typ", "System"' },
        { front: 'X sounds like...', back: 'ks', hint: 'Like in "Max", "Axt"' },
        { front: 'Tsch sounds like...', back: 'ch (like in "church")', hint: 'Like in "Tschüss", "Deutsch"' },
        { front: 'M sounds like...', back: 'm', hint: 'Like in "Mutter"' },
        { front: 'N sounds like...', back: 'n', hint: 'Like in "Natur"' },
        { front: 'L sounds like...', back: 'l', hint: 'Like in "Liebe"' },
        { front: 'K sounds like...', back: 'k', hint: 'Like in "Kind"' },
        { front: 'P sounds like...', back: 'p', hint: 'Like in "Papa"' },
        { front: 'T sounds like...', back: 't', hint: 'Like in "Tante"' },
        { front: 'H (at start) sounds like...', back: 'h', hint: 'Like in "Hallo"' },
        { front: 'H (after vowel) sounds like...', back: 'silent (lengthens vowel)', hint: 'Like in "sehen", "gehen"' },
        { front: 'F sounds like...', back: 'f', hint: 'Like in "Fisch"' },
        { front: 'G (at start) sounds like...', back: 'g', hint: 'Like in "gut"' }
    ],
    ep3: [
        { front: '0', back: 'null', hint: 'Number' },
        { front: '1', back: 'eins', hint: 'Number' },
        { front: '2', back: 'zwei', hint: 'Number' },
        { front: '3', back: 'drei', hint: 'Number' },
        { front: '4', back: 'vier', hint: 'Number' },
        { front: '5', back: 'fünf', hint: 'Number' },
        { front: '6', back: 'sechs', hint: 'Number' },
        { front: '7', back: 'sieben', hint: 'Number' },
        { front: '8', back: 'acht', hint: 'Number' },
        { front: '9', back: 'neun', hint: 'Number' },
        { front: '10', back: 'zehn', hint: 'Number' },
        { front: '11', back: 'elf', hint: 'Number' },
        { front: '12', back: 'zwölf', hint: 'Number' },
        { front: '13', back: 'dreizehn', hint: '3 + 10' },
        { front: '14', back: 'vierzehn', hint: '4 + 10' },
        { front: '15', back: 'fünfzehn', hint: '5 + 10' },
        { front: '16', back: 'sechzehn', hint: 'drops the s from sechs' },
        { front: '17', back: 'siebzehn', hint: 'drops the en from sieben' },
        { front: '18', back: 'achtzehn', hint: '8 + 10' },
        { front: '19', back: 'neunzehn', hint: '9 + 10' },
        { front: '20', back: 'zwanzig', hint: 'Tens' },
        { front: '21', back: 'einundzwanzig', hint: '1 and 20' },
        { front: '22', back: 'zweiundzwanzig', hint: '2 and 20' },
        { front: '23', back: 'dreiundzwanzig', hint: '3 and 20' },
        { front: '24', back: 'vierundzwanzig', hint: '4 and 20' },
        { front: '25', back: 'fünfundzwanzig', hint: '5 and 20' },
        { front: '30', back: 'dreißig', hint: 'Uses ß instead of z' },
        { front: '31', back: 'einunddreißig', hint: '1 and 30' },
        { front: '40', back: 'vierzig', hint: 'Tens' },
        { front: '42', back: 'zweiundvierzig', hint: '2 and 40' },
        { front: '50', back: 'fünfzig', hint: 'Tens' },
        { front: '55', back: 'fünfundfünfzig', hint: '5 and 50' },
        { front: '60', back: 'sechzig', hint: 'drops s from sechs' },
        { front: '70', back: 'siebzig', hint: 'drops en from sieben' },
        { front: '80', back: 'achtzig', hint: 'Tens' },
        { front: '90', back: 'neunzig', hint: 'Tens' },
        { front: '100', back: 'hundert', hint: 'Hundreds' },
        { front: '101', back: 'hunderteins', hint: '100 + 1' },
        { front: '200', back: 'zweihundert', hint: '2 + 100' },
        { front: '1000', back: 'tausend', hint: 'Thousands' },
        { front: 'plus (+)', back: 'plus', hint: 'Math' },
        { front: 'minus (-)', back: 'minus', hint: 'Math' },
        { front: 'times (x)', back: 'mal', hint: 'Math' },
        { front: 'divided by (/)', back: 'durch', hint: 'Math' },
        { front: 'equals (=)', back: 'ist / macht', hint: 'Math' },
        { front: '1 + 1 = 2', back: 'eins plus eins ist zwei', hint: 'Math phrase' },
        { front: '10 - 5 = 5', back: 'zehn minus fünf ist fünf', hint: 'Math phrase' },
        { front: '3 x 4 = 12', back: 'drei mal vier ist zwölf', hint: 'Math phrase' },
        { front: '20 / 2 = 10', back: 'zwanzig durch zwei ist zehn', hint: 'Math phrase' },
        { front: 'How old are you?', back: 'Wie alt bist du?', hint: 'Age question' }
    ],
    ep4: [
        { front: 'I am', back: 'ich bin', hint: 'sein (to be)' },
        { front: 'You are (informal)', back: 'du bist', hint: 'sein (to be)' },
        { front: 'He is', back: 'er ist', hint: 'sein (to be)' },
        { front: 'She is', back: 'sie ist', hint: 'sein (to be)' },
        { front: 'It is', back: 'es ist', hint: 'sein (to be)' },
        { front: 'We are', back: 'wir sind', hint: 'sein (to be)' },
        { front: 'You all are', back: 'ihr seid', hint: 'sein (to be)' },
        { front: 'They are', back: 'sie sind', hint: 'sein (to be)' },
        { front: 'You are (formal)', back: 'Sie sind', hint: 'sein (to be)' },
        { front: 'I have', back: 'ich habe', hint: 'haben (to have)' },
        { front: 'You have (informal)', back: 'du hast', hint: 'haben (to have)' },
        { front: 'He has', back: 'er hat', hint: 'haben (to have)' },
        { front: 'She has', back: 'sie hat', hint: 'haben (to have)' },
        { front: 'It has', back: 'es hat', hint: 'haben (to have)' },
        { front: 'We have', back: 'wir haben', hint: 'haben (to have)' },
        { front: 'You all have', back: 'ihr habt', hint: 'haben (to have)' },
        { front: 'They have', back: 'sie haben', hint: 'haben (to have)' },
        { front: 'You have (formal)', back: 'Sie haben', hint: 'haben (to have)' },
        { front: 'My name is... (I am called)', back: 'Ich heiße...', hint: 'Self-introduction' },
        { front: 'My name is... (My name is)', back: 'Mein Name ist...', hint: 'Self-introduction' },
        { front: 'I am... (I am Anuj)', back: 'Ich bin...', hint: 'Self-introduction' },
        { front: 'What is your name? (informal)', back: 'Wie heißt du?', hint: 'Asking name' },
        { front: 'What is your name? (formal)', back: 'Wie heißen Sie?', hint: 'Asking name' },
        { front: 'I am from India', back: 'Ich komme aus Indien', hint: 'Origin' },
        { front: 'I am from Germany', back: 'Ich komme aus Deutschland', hint: 'Origin' },
        { front: 'Where do you come from? (informal)', back: 'Woher kommst du?', hint: 'Asking origin' },
        { front: 'Where do you come from? (formal)', back: 'Woher kommen Sie?', hint: 'Asking origin' },
        { front: 'I live in Berlin', back: 'Ich wohne in Berlin', hint: 'Residence' },
        { front: 'Where do you live? (informal)', back: 'Wo wohnst du?', hint: 'Asking residence' },
        { front: 'Where do you live? (formal)', back: 'Wo wohnen Sie?', hint: 'Asking residence' },
        { front: 'I speak English and German', back: 'Ich spreche Englisch und Deutsch', hint: 'Languages' },
        { front: 'What do you speak? (informal)', back: 'Was sprichst du?', hint: 'Asking languages' },
        { front: 'What do you speak? (formal)', back: 'Was sprechen Sie?', hint: 'Asking languages' },
        { front: 'I am a student (male)', back: 'Ich bin Student', hint: 'Profession' },
        { front: 'I am a student (female)', back: 'Ich bin Studentin', hint: 'Profession' },
        { front: 'I am a teacher (male)', back: 'Ich bin Lehrer', hint: 'Profession' },
        { front: 'I am a teacher (female)', back: 'Ich bin Lehrerin', hint: 'Profession' },
        { front: 'What is your profession? (informal)', back: 'Was bist du von Beruf?', hint: 'Asking profession' },
        { front: 'What is your profession? (formal)', back: 'Was sind Sie von Beruf?', hint: 'Asking profession' },
        { front: 'I am 25 years old', back: 'Ich bin 25 Jahre alt', hint: 'Age' },
        { front: 'I have a car', back: 'Ich habe ein Auto', hint: 'Possession' },
        { front: 'I have time', back: 'Ich habe Zeit', hint: 'Possession' },
        { front: 'I am hungry', back: 'Ich habe Hunger', hint: 'Idiom (I have hunger)' },
        { front: 'I am thirsty', back: 'Ich habe Durst', hint: 'Idiom (I have thirst)' },
        { front: 'I am right', back: 'Ich habe Recht', hint: 'Idiom (I have right)' },
        { front: 'I am afraid', back: 'Ich habe Angst', hint: 'Idiom (I have fear)' },
        { front: 'I am tired', back: 'Ich bin müde', hint: 'State' },
        { front: 'The weather is nice', back: 'Das Wetter ist schön', hint: 'Description' },
        { front: 'We are here', back: 'Wir sind hier', hint: 'Location' },
        { front: 'The book is interesting', back: 'Das Buch ist interessant', hint: 'Description' }
    ],
    ep5: generateVerbsDeck(),
    ep6: [
        { front: 'Good morning!', back: 'Guten Morgen!', hint: 'Greeting (until ~10am)' },
        { front: 'Good day! / Hello!', back: 'Guten Tag!', hint: 'Greeting (all day)' },
        { front: 'Good evening!', back: 'Guten Abend!', hint: 'Greeting (after 6pm)' },
        { front: 'Good night!', back: 'Gute Nacht!', hint: 'Leaving for bed' },
        { front: 'Hello! (informal)', back: 'Hallo!', hint: 'Common greeting' },
        { front: 'Hi! (informal)', back: 'Hi!', hint: 'Casual greeting' },
        { front: 'Greetings! (Southern Germany)', back: 'Grüß Gott!', hint: 'Regional greeting' },
        { front: 'Hello! (Switzerland/South)', back: 'Servus!', hint: 'Regional greeting' },
        { front: 'Hello! (Northern Germany)', back: 'Moin!', hint: 'Regional greeting' },
        { front: 'Goodbye! (formal)', back: 'Auf Wiedersehen!', hint: 'Farewell' },
        { front: 'Bye! (informal)', back: 'Tschüss!', hint: 'Casual farewell' },
        { front: 'See you later!', back: 'Bis später!', hint: 'Farewell' },
        { front: 'See you soon!', back: 'Bis bald!', hint: 'Farewell' },
        { front: 'See you tomorrow!', back: 'Bis morgen!', hint: 'Farewell' },
        { front: 'Have a nice day!', back: 'Schönen Tag noch!', hint: 'Polite farewell' },
        { front: 'Have a nice weekend!', back: 'Schönes Wochenende!', hint: 'Polite farewell' },
        { front: 'How are you? (formal)', back: 'Wie geht es Ihnen?', hint: 'Asking well-being' },
        { front: 'How are you? (informal)', back: 'Wie geht es dir?', hint: 'Asking well-being' },
        { front: 'How\'s it going? (casual)', back: 'Wie geht\'s?', hint: 'Short form' },
        { front: 'I am doing well', back: 'Mir geht es gut', hint: 'Response' },
        { front: 'Good, thanks', back: 'Gut, danke', hint: 'Short response' },
        { front: 'Very good', back: 'Sehr gut', hint: 'Response' },
        { front: 'Not so good', back: 'Nicht so gut', hint: 'Response' },
        { front: 'Bad', back: 'Schlecht', hint: 'Response' },
        { front: 'So-so', back: 'Es geht', hint: 'Response' },
        { front: 'And you? (formal)', back: 'Und Ihnen?', hint: 'Return question' },
        { front: 'And you? (informal)', back: 'Und dir?', hint: 'Return question' },
        { front: 'Please', back: 'Bitte', hint: 'Politeness' },
        { front: 'Thank you', back: 'Danke', hint: 'Gratitude' },
        { front: 'Thank you very much', back: 'Danke schön / Vielen Dank', hint: 'Gratitude' },
        { front: 'You are welcome', back: 'Bitte schön / Gern geschehen', hint: 'Response to thanks' },
        { front: 'Excuse me', back: 'Entschuldigung', hint: 'Getting attention / minor apology' },
        { front: 'I am sorry', back: 'Es tut mir leid', hint: 'Apology' },
        { front: 'No problem', back: 'Kein Problem', hint: 'Reassurance' },
        { front: 'Yes', back: 'Ja', hint: 'Agreement' },
        { front: 'No', back: 'Nein', hint: 'Disagreement' },
        { front: 'Maybe', back: 'Vielleicht', hint: 'Uncertainty' },
        { front: 'I don\'t know', back: 'Ich weiß (es) nicht', hint: 'Lack of knowledge' },
        { front: 'I understand', back: 'Ich verstehe', hint: 'Comprehension' },
        { front: 'I don\'t understand', back: 'Ich verstehe nicht', hint: 'Lack of comprehension' },
        { front: 'Do you speak English? (formal)', back: 'Sprechen Sie Englisch?', hint: 'Question' },
        { front: 'Do you speak English? (informal)', back: 'Sprichst du Englisch?', hint: 'Question' },
        { front: 'Please speak slowly', back: 'Bitte sprechen Sie langsam', hint: 'Request' },
        { front: 'Could you repeat that?', back: 'Können Sie das bitte wiederholen?', hint: 'Request' },
        { front: 'What does ... mean?', back: 'Was bedeutet ...?', hint: 'Asking for meaning' },
        { front: 'How do you say ... in German?', back: 'Wie sagt man ... auf Deutsch?', hint: 'Asking for translation' },
        { front: 'Cheers!', back: 'Prost!', hint: 'Drinking' },
        { front: 'Enjoy your meal!', back: 'Guten Appetit!', hint: 'Eating' },
        { front: 'Bless you!', back: 'Gesundheit!', hint: 'After someone sneezes' },
        { front: 'Welcome!', back: 'Willkommen!', hint: 'Greeting' }
    ]
};"""

with open(app_js_path, "r", encoding="utf-8") as f:
    content = f.read()

# Replace the DECKS variable. It starts at `const DECKS = {` and ends right before `document.addEventListener`
pattern = re.compile(r'const DECKS = \{.*?\n};\n', re.DOTALL)
content = pattern.sub(new_decks + "\n", content)

with open(app_js_path, "w", encoding="utf-8") as f:
    f.write(content)

print("Flashcard content expanded in app.js")
