const fs = require('fs');
let code = fs.readFileSync('generateGuidedSets.cjs', 'utf-8');
const match = code.match(/const guidedSets = (\[[\s\S]*\]);/);
if (!match) { console.log('No match'); process.exit(1); }
let sets = eval(match[1]);

// Deep interview Q&As for every set — "If asked: ... Say: ..." style
const deepQA = {

  set_encode_decode: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What command do you use to find an airline code?'",
    "Say: 'I use DNA followed by the airline name, for example DNA INDIGO. To decode a numeric",
    "      airline code I use DAC with the code. For city codes I use DC with the city name",
    "      to encode or DC with the code to decode.'",
    "",
    "If asked: 'How do you find the IATA code for a city?'",
    "Say: 'I use DC followed by the city name — for example DC DELHI — which returns the",
    "      IATA city code DEL. To decode, I enter DC DEL and the system returns the city name.'",
    "",
    "If asked: 'Why is encoding important in Amadeus?'",
    "Say: 'Amadeus uses IATA codes for all entries. If I enter a wrong code or do not know",
    "      the correct code, the system will return an error or retrieve the wrong result.",
    "      Encoding/decoding ensures I use precise, standardized IATA identifiers.'",
  ],

  set_time_currency: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you check the current time at a destination?'",
    "Say: 'I use DATI followed by the city code — for example DATI LHR — to display",
    "      the current local time and date at London Heathrow.'",
    "",
    "If asked: 'How do you convert currencies in Amadeus?'",
    "Say: 'I use DC followed by the amount, the source currency code, and the target",
    "      currency code — for example DC 5000 INR/USD — to see the converted amount',",
    "      using the current IATA exchange rate.'",
    "",
    "If asked: 'What is the difference between GMT and local time?'",
    "Say: 'GMT is the universal reference time. Local time differs based on the",
    "      time zone and any daylight saving offset. Amadeus flight times are",
    "      displayed in local time. I use DATI to check local time at any city.'",
  ],

  set_pnr_creation: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'Walk me through creating a PNR from scratch and issuing a ticket.'",
    "Say: 'First I check availability with AN — for example AN25SEPDELLHR. I select",
    "      a flight and sell seats using SS — for example SS1Y1 for one seat in Y class",
    "      on line 1. I then create the mandatory PNR elements: passenger name with NM,",
    "      contact with AP, ticketing arrangement with TKOK, and received-from with RF.",
    "      I price the itinerary with FXP which creates the TST, verify with TQT,",
    "      add form of payment with FP, and end the PNR with ER. After retrieving with RT",
    "      I issue the ticket using TTP and verify the e-ticket with TWD.'",
    "",
    "If asked: 'What happens if you miss the RF element before ER?'",
    "Say: 'Amadeus will reject the End Transaction and return an error asking for",
    "      the Received From element. RF is mandatory. It records who authorised",
    "      the booking and is part of the PNR audit trail visible in RH.'",
    "",
    "If asked: 'What is the difference between ER and ET?'",
    "Say: 'ER ends the transaction and redisplays the PNR with the new record locator.",
    "      ET ends the transaction and clears the work area — the PNR is saved but",
    "      you are returned to a blank screen. Use ER when you want to see the saved PNR.'",
    "",
    "If asked: 'What is FXP and when do you use it?'",
    "Say: 'FXP is the standard itinerary pricing command. It prices the PNR using",
    "      the booking classes already stored and creates a TST. I use it after the",
    "      mandatory elements are in place and before adding the form of payment.",
    "      FXX is the alternative that prices without creating a TST — useful for",
    "      showing the fare to a passenger before committing.'",
  ],

  set_split_pnr: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you split a PNR?'",
    "Say: 'I retrieve the parent PNR with RT. I identify the passenger name element",
    "      number I want to separate and enter SP followed by the number — for example",
    "      SP2 to split passenger 2. Amadeus creates an associate PNR containing the",
    "      split passenger. I enter RF and use EF to End and File the associate PNR.",
    "      Amadeus returns me to the parent PNR. I enter RF again and end the parent",
    "      with ET. The two PNRs remain linked through AXR.'",
    "",
    "If asked: 'Why do you use EF instead of ER or ET for the split PNR?'",
    "Say: 'EF means End and File — it saves the associate PNR without displaying it",
    "      again and returns control to the parent PNR so I can complete that transaction.",
    "      ER would redisplay the associate and ET would end both in an incomplete state.'",
    "",
    "If asked: 'How do you retrieve the linked associate PNR later?'",
    "Say: 'While the parent PNR is retrieved, I enter RTAXR to display the AXR",
    "      Associated Record Indexing link. I can then select the associated PNR",
    "      from the list. I can also retrieve it directly by its own record locator.'",
    "",
    "If asked: 'Can you split multiple passengers at once?'",
    "Say: 'Yes. I use SP followed by multiple passenger numbers — for example SP2,4",
    "      to split passengers 2 and 4 simultaneously, or SP3,4,5-7 for a range.'",
  ],

  set_arnk: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is an ARNK segment and when would you use it?'",
    "Say: 'ARNK stands for Arrival Not Known. I use it when there is a surface gap",
    "      between two air segments — meaning the passenger is travelling by another",
    "      mode of transport between the arrival city of one flight and the departure",
    "      city of the next. For example if a passenger flies DEL to LHR and then",
    "      LHR to Paris by Eurostar before flying CDG to DEL, I insert SIARNK between",
    "      the LHR arrival and the CDG departure to maintain itinerary continuity.'",
    "",
    "If asked: 'How do you insert an ARNK for a specific passenger?'",
    "Say: 'I use SIARNK20NOV/P2 — where 20NOV is the date of the surface leg and",
    "      P2 specifies passenger 2. Without a passenger association, the ARNK applies",
    "      to all passengers in the PNR.'",
    "",
    "If asked: 'Can you have two ARNKs in one PNR?'",
    "Say: 'Two ARNKs can exist if there are two separate surface gaps, but an ARNK",
    "      cannot immediately precede another ARNK. Amadeus will reject consecutive",
    "      ARNKs as an invalid itinerary.'",
  ],

  set_rebooking: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you rebook a passenger to a different flight?'",
    "Say: 'I retrieve the PNR with RT and check the availability of the new flight",
    "      using AN. I cancel the original segment if required, then sell the new",
    "      flight using SS. Alternatively, for a date change on the same flight I",
    "      can use SB followed by the new date and segment number — for example",
    "      SB28SEP1. I always verify the new segment status is HK, update the TST",
    "      with FXP, add RF and end the transaction with ER.'",
    "",
    "If asked: 'What status code should a confirmed segment show?'",
    "Say: 'HK — Holding Confirmed. If the segment shows HL it is on the waitlist,",
    "      HX means the airline has cancelled it, and UN means unable to confirm.",
    "      Only HK means the seat is genuinely confirmed.'",
  ],

  set_atc: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is ATC and what does it do?'",
    "Say: 'ATC stands for Amadeus Ticket Changer. It is an automated tool that",
    "      calculates the fare difference, tax difference and applicable penalty",
    "      for a voluntary or involuntary itinerary change, using the original",
    "      ticket data and the applicable fare rules. For voluntary changes I use",
    "      FXF for informative pricing and FXQ to confirm. For involuntary airline",
    "      disruptions I use FXI. ATC supports both unused and partially used tickets.'",
    "",
    "If asked: 'What is the difference between FXF and FXQ?'",
    "Say: 'FXF is the ATC informative pricing command — it calculates the change",
    "      cost but does not update the PNR or TST. I use it to tell the passenger",
    "      the total amount due. FXQ is the confirmed pricing — it updates the TST",
    "      and commits the reissue. I only run FXQ after the passenger agrees to pay.'",
    "",
    "If asked: 'When is ATC not available?'",
    "Say: 'ATC may not be available if the airline has not filed Category 31 voluntary",
    "      change conditions, if the ticket is a complex interline itinerary without",
    "      ATC support, or if the system cannot match the original ticket data.",
    "      In those cases I perform a manual exchange using TTU/TTK/EXCH/FO/TTP.'",
  ],

  set_retrieve_name: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you retrieve a PNR if you only have the passenger name?'",
    "Say: 'I use RT/SMITH to retrieve all PNRs containing the surname SMITH.",
    "      If there are multiple results, I select with RT1, RT2 etc.",
    "      To narrow it down I can add the first initial: RT/SMITH/J,",
    "      or combine with a date: RT/12AUG-SMITH,",
    "      or with a flight: RT KL153/12AUG-SMITH.'",
    "",
    "If asked: 'What is the difference between RT and RO?'",
    "Say: 'RT retrieves a PNR that is stored in the Amadeus system.",
    "      RO is used to claim or retrieve a PNR from another GDS or airline",
    "      system — for example from a codeshare partner system — using their",
    "      record locator. After RO the PNR is transferred to my office.'",
  ],

  set_fare_rule: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you check fare rules in Amadeus?'",
    "Say: 'I use FQN after a fare display to view the fare notes and conditions.",
    "      FQN shows all applicable fare rule categories including advance purchase,",
    "      minimum/maximum stay, penalties and change conditions.",
    "      I use FQR for routing information and FQS for booking code details.",
    "      For a quick summary of key rules I use FQF1 or FWR.'",
    "",
    "If asked: 'A passenger asks if they can get a refund. How do you check?'",
    "Say: 'I open the fare display with FQD and then use FQN to check Category 33",
    "      — Ticket Refunds. This tells me whether the fare is non-refundable,",
    "      partially refundable, or fully refundable, and what penalty applies.'",
  ],

  set_fare_comparison: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you compare different fare options for a route?'",
    "Say: 'I use FQD followed by the route — for example FQD DELLHR — to display",
    "      all available fares sorted by price. I can filter by cabin, fare basis,",
    "      passenger type and other criteria. I then use FQN on a specific fare",
    "      line to check its conditions before recommending it to the passenger.'",
    "",
    "If asked: 'What is the difference between FXP and FXB?'",
    "Say: 'FXP prices the PNR using the booking class already stored and creates a TST.",
    "      FXB finds the cheapest applicable fare, rebooks the PNR into the required",
    "      booking class automatically, and creates a TST.",
    "      FXP = Price the Present booking. FXB = Best price with automatic rebook.'",
  ],

  set_name_correction: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you correct a passenger name in Amadeus?'",
    "Say: 'First I retrieve the PNR with RT and identify the name element number.",
    "      For a minor correction I use the appropriate name change entry.",
    "      If the ticket has already been issued, I must check the airline policy",
    "      — some airlines allow minor corrections through a reissue, others do not.",
    "      For pre-ticketing corrections, I cancel the original name element",
    "      and re-enter the correct name, then add RF and end with ER.'",
    "",
    "If asked: 'What is the difference between a name correction and a name change?'",
    "Say: 'A name correction fixes a typographical error — for example CHAUDHERY",
    "      corrected to CHAUDHARY. A name change is a transfer to a completely",
    "      different person, which most airlines do not permit. The distinction",
    "      is important because airlines may allow corrections but not changes,",
    "      and the allowance depends on the fare rules and airline policy.'",
  ],

  set_refunds: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you process a refund in Amadeus?'",
    "Say: 'The master refund workflow is TRF → TRFT → TRFU → TRFP.",
    "      I start with TRF followed by the ticket number to initiate the refund.",
    "      TRFT calculates the refund amount based on the applicable fare conditions.",
    "      TRFU updates the refund record.",
    "      TRFP processes/pays the refund and generates the refund document.",
    "      Finally I verify the ticket coupon status is REFUNDED using TWD.'",
    "",
    "If asked: 'What is the difference between a void and a refund?'",
    "Say: 'A void reverses a ticket transaction before BSP confirmation — it is as if",
    "      the ticket was never issued. The command is TRDC. A refund processes a formal",
    "      return of the fare and taxes through the BSP and generates a refund notice.",
    "      Voids are only possible within the permitted void window before BSP closes.'",
  ],

  set_history: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you investigate what changes were made to a PNR?'",
    "Say: 'I retrieve the PNR with RT and then display the full history using RH.",
    "      RH shows every modification in sequence with step numbers, action codes,",
    "      agent signs, office IDs and timestamps. I use RHA for air segment history,",
    "      RHN for name history, RHG for SSR/OSI, RHK for ticketing and RHF for fare",
    "      elements. This lets me trace exactly what changed, when, and who made the change.'",
    "",
    "If asked: 'What do the action codes in PNR history mean?'",
    "Say: 'O = Original entry, A = Added, C = Changed, X = Cancelled.",
    "      Combined with element codes: ON = Original Name, CS = Changed Status,",
    "      XS = Cancelled Segment, AF = Added Fare element. The step numbers show",
    "      when an element was first created versus when it was modified or cancelled.'",
  ],

  set_master_pricer: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is the Master Pricer and when would you use it?'",
    "Say: 'The Master Pricer is an Amadeus availability and pricing tool that",
    "      simultaneously searches across multiple airlines and cabin classes to",
    "      find the best fare options for a given route and date. The basic command",
    "      is FLQD followed by the route and date parameters. Unlike AN which shows",
    "      one flight at a time, Master Pricer returns a ranked list of fare/flight",
    "      combinations — very useful when the passenger wants the cheapest option.'",
    "",
    "If asked: 'How is FXB different from the Master Pricer?'",
    "Say: 'The Master Pricer (FLQD) is used during the shopping phase — before",
    "      selling — to find the best fare-and-flight combination.",
    "      FXB is used after a booking is already made to reprice and rebook",
    "      the PNR into the cheapest available fare class automatically.'",
  ],

  set_void: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you void a ticket?'",
    "Say: 'I retrieve the PNR with RT and display the ticket with TWD to confirm",
    "      the ticket number and that it has not yet been reported to BSP.",
    "      I then enter TRDC followed by the ticket number to void it.",
    "      I verify the coupon status has changed to VOID using TWD.',",
    "      The key restriction is that voiding must happen before BSP confirmation",
    "      — after that, a refund must be processed instead.'",
    "",
    "If asked: 'What is TRDC?'",
    "Say: 'TRDC stands for Ticket/Document Cancel. It is the Amadeus command",
    "      used to void a ticket. Memory hook: TR = Ticket Record, DC = Document Cancel.'",
  ],

  set_involuntary: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is an involuntary change and how do you handle it?'",
    "Say: 'An involuntary change is a disruption caused by the airline rather than",
    "      the passenger — for example a flight cancellation, schedule change or",
    "      route amendment. The airline typically rebooks the passenger on an",
    "      alternative flight. I retrieve the PNR with RT, verify the original",
    "      ticket with TWD, confirm the airline has provided the new itinerary,",
    "      and then run FXI for an ATC involuntary reissue. FXI automatically",
    "      prepares the TST with the original fare, taxes, endorsement FE SKCHG,",
    "      FO and FPO without any additional collection or penalty.',",
    "      I then check with TQT/TQR and issue with TTP.'",
    "",
    "If asked: 'Can a passenger be charged for an involuntary change?'",
    "Say: 'No — for a genuine involuntary change caused by the airline, the passenger",
    "      should not pay a change penalty or additional collection. FXI reflects this",
    "      — it carries the original fare and taxes without adding charges.",
    "      If the passenger voluntarily chooses a more expensive alternative, that",
    "      portion may be collected, depending on airline policy.'",
  ],

  set_schedule_change: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'A passenger calls saying the airline changed their flight time by 3 hours. What do you do?'",
    "Say: 'First I retrieve the PNR with RT and check the current segment status.",
    "      I display the PNR history with RH or RHA to confirm the schedule change",
    "      and note when it was made. I check the new flight details and compare",
    "      with the original. If the change is significant, the passenger may be",
    "      entitled to a free rebooking or refund per the airline policy.",
    "      If rebooking, I check availability with AN, cancel the old segment,",
    "      sell the preferred alternative, and if a ticket was issued,",
    "      process a reissue through ATC FXI or a manual involuntary exchange.',",
    "      I always verify the final state with TWD.'",
  ],

  set_queues: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What are queues in Amadeus and how do you work them?'",
    "Say: 'Queues are a structured workflow system for managing PNRs requiring action.",
    "      Airlines, offices and systems use queues to send PNRs that need attention.",
    "      To access a queue I use QD to display the queue list, enter the queue to",
    "      retrieve the first PNR, action the booking, then move to the next with QN",
    "      or remove the PNR from the queue with QR. Common queues include schedule",
    "      change queues from airlines, ticketing reminder queues and waitlist queues.'",
    "",
    "If asked: 'How do you move a PNR to a queue?'",
    "Say: 'I use QE followed by the queue number and category — for example QE3C1",
    "      to place the PNR on queue 3 category 1. The PNR can then be retrieved",
    "      and actioned by any agent with access to that queue.'",
  ],

  set_unflown_reissue: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you manually reissue an unflown ticket for a voluntary change?'",
    "Say: 'First I retrieve the PNR with RT and display the original e-ticket with TWD.",
    "      I check the original TST and fare rules to determine whether the change is",
    "      permitted and what penalty applies. I then rebook the new itinerary, price it",
    "      with FXP, and compare the original and new fare, taxes and penalty to calculate",
    "      the additional collection or residual value. I update the TST, set it into",
    "      exchange mode with TTK/EXCH, create the FO from the original FA/FHE line,",
    "      update the FOP, commission and endorsement as required, remove the TST flag",
    "      with TTF, add RF and end the PNR, then issue using TTP/EXCH and verify",
    "      the new ticket with TWD.'",
    "",
    "If asked: 'How do you check if a voluntary change is permitted?'",
    "Say: 'I use FQN on the fare display or from the TST to read Category 31 —",
    "      Voluntary Changes. This tells me whether changes are permitted, what",
    "      advance notice is required, and what penalty applies. If no category",
    "      31 exists, the fare is typically non-changeable.'",
  ],

  set_partially_flown_reissue: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How is a partially flown ticket reissue different from an unflown reissue?'",
    "Say: 'First I check the e-ticket with TWD to identify which coupons are USED",
    "      and which remain OPEN. I do not treat the flown portion as new transportation.",
    "      I check the original fare rules and calculate the reissue based only on the",
    "      remaining transportation. If there is a past-dated segment, I make sure it is",
    "      properly excluded or associated for the pricing calculation. I then rebook",
    "      the remaining portion, update the TST, set it to exchange mode using TTK/EXCH,",
    "      create the FO from the original ticket, update penalty taxes and form of payment,",
    "      remove the TST flag with TTF, issue the exchange and verify the new ticket with TWD.",
    "      For ATC, I must specify all unflown segments using FXF/S... and FXQ/S...'",
    "",
    "If asked: 'What does coupon status tell you?'",
    "Say: 'OPEN = coupon is unused and valid for travel.",
    "      USED = coupon has been lifted at the departure airport for that sector.",
    "      VOID = ticket has been voided.",
    "      REFUNDED = refund has been processed for that coupon.",
    "      SUSPENDED = coupon is on hold, often during an exchange.",
    "      I always read coupon status in TWD before any reissue or refund action.'",
  ],

  set_involuntary_changes: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is the difference between a voluntary and involuntary reissue?'",
    "Say: 'Voluntary: The passenger requested the change. I use FXF then FXQ through ATC.",
    "      Penalties and fare differences may apply per Category 31.",
    "      Involuntary: The airline caused the change. I use FXI through ATC.",
    "      No penalty or additional collection. FXI carries original fare, taxes and",
    "      endorsement. The endorsement FE SKCHG is added automatically.",
    "      Key distinction: Always confirm who initiated the change before choosing FXQ vs FXI.'",
  ],

  set_involuntary_atc: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'Walk me through the complete FXI workflow.'",
    "Say: 'I retrieve the PNR with RT and verify the original ticket with TWD.",
    "      The airline should have already provided the new itinerary in the PNR.",
    "      I run FXI — Amadeus automatically creates a TST with the original fare,",
    "      taxes, FO from the original ticket, FPO, and the endorsement FE SKCHG.",
    "      I check the TST with TQT and review the ATC reissue panel with TQR to",
    "      confirm no additional collection is shown. I then issue with TTP and",
    "      verify the new ticket coupon status is OPEN using TWD.'",
    "",
    "If asked: 'What endorsement does FXI add automatically?'",
    "Say: 'FXI adds the endorsement FE SKCHG — meaning Schedule Change —",
    "      which signals to the airline that the reissue was caused by an",
    "      involuntary disruption and no penalty is applicable.'",
  ],

  set_involuntary_manual: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'When would you do a manual involuntary exchange instead of FXI?'",
    "Say: 'FXI may not be available if the airline does not support ATC Involuntary,",
    "      if the itinerary is complex interline, or if the system cannot automatically",
    "      match the original ticket. In those cases I perform the exchange manually:",
    "      I rebook the authorized new itinerary, update the TST with TTU,",
    "      place it into exchange mode with TTK/EXCH, create the FO from the FA/FHE line,",
    "      add the involuntary endorsement manually, remove the TST flag with TTF,",
    "      add RF and end with ER, then issue with TTP/EXCH/INV/RT.'",
    "",
    "If asked: 'What is the difference between TTP/EXCH and TTP/EXCH/INV/RT?'",
    "Say: 'TTP/EXCH is used for voluntary exchanges.",
    "      TTP/EXCH/INV/RT specifically flags the issuance as an involuntary exchange,",
    "      which is important for BSP reporting and ensures the correct exchange",
    "      reason code is attached to the ticket.'",
  ],

  set_ticket_void: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is the difference between void, refund and exchange?'",
    "Say: 'Void (TRDC): Cancels the ticket before BSP confirmation.",
    "      No refund record is generated — the transaction is simply reversed.",
    "      Refund (TRF → TRFT → TRFU → TRFP): Formally returns the fare/taxes",
    "      through BSP after the ticket has been reported. Generates a refund notice.",
    "      Exchange/Reissue (TTK/EXCH or ATC FXQ/FXI): A new ticket is issued",
    "      based on the original, reflecting the changed itinerary, fare difference",
    "      and applicable penalty. The original ticket coupons are marked EXCHANGED.'",
  ],

  set_pricing_booked: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is the difference between FXP and FXX?'",
    "Say: 'FXP prices the PNR using the booked classes and creates a stored TST.",
    "      FXX prices without creating a TST — useful for checking the fare without",
    "      committing it to the PNR. Memory hook: P = Prepare/Price with TST.",
    "      X = eXamine only, no TST.'",
    "",
    "If asked: 'How do you check what is in the TST?'",
    "Say: 'I use TQT to display the stored TST. TQT/T1 displays TST number 1",
    "      specifically when there are multiple TSTs in the PNR.",
    "      The TST shows passenger, fare basis, total fare, taxes and FOP.'",
  ],

  set_pricing_master: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you find the cheapest available fare for a route?'",
    "Say: 'I use the Master Pricer — FLQD or MPD depending on the configuration —",
    "      which searches across airlines and cabins simultaneously and ranks results",
    "      by price. I select the best option and confirm with the appropriate",
    "      sell entry. Alternatively I can use FXB after making a booking to",
    "      automatically rebook into the cheapest applicable fare class.'",
  ],

  set_purged_pnr: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'A passenger travelled 8 months ago and needs proof of travel. What do you do?'",
    "Say: 'If the PNR is purged, RT will return NOT FOUND. I submit a past-date recall",
    "      using RPD/RLC-[locator]/[date]. I check RLD to see if the request has been",
    "      processed, and once it appears as PROCESSED I use RLDT1 to open the PDR.",
    "      If I only need the ticket details I can use TWD/TKT followed by the",
    "      ticket number directly, which works independently of the PNR.'",
    "",
    "If asked: 'RPD immediately retrieves the PNR, correct?'",
    "Say: 'This is a common misconception. RPD submits a request — it does not",
    "      immediately open the PNR. The retrieval is a deferred/batch process.",
    "      I must use RLD to check the request status and RLDT to open the result",
    "      once it is marked PROCESSED.'",
  ],

  set_pnr_history: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you prove a booking was modified without the passenger's consent?'",
    "Say: 'I retrieve the PNR with RT and display the history with RH or the",
    "      relevant filtered history — RHA for air segments. The history shows",
    "      every change with the agent sign, office ID, date and time.",
    "      I locate the relevant entry, read the action code (C = Changed),",
    "      compare the step numbers before and after the modification, and",
    "      note who made the change and from which office.",
    "      This constitutes a full audit trail for dispute resolution.'",
  ],

  set_refund_vol_unflown: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you process a refund on a fully unused ticket?'",
    "Say: 'I retrieve the PNR and verify the ticket with TWD to confirm all",
    "      coupons are OPEN. I initiate the refund with TRF/TKT[number],",
    "      use TRFT to calculate the refund amount based on Category 33 conditions,",
    "      TRFU to update, and TRFP to process and generate the refund document.",
    "      I verify the coupon status has changed to REFUNDED using TWD.",
    "      If the passenger does not agree after TRFT I can cancel with TRDX.'",
  ],

  set_refund_vol_partial: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How is a partial refund different from a full refund?'",
    "Say: 'For a partially flown ticket, only the unused coupons are eligible for refund.",
    "      I verify TWD to confirm which coupons are USED and which are OPEN.",
    "      The refund calculation covers only the unused transportation, and the fare",
    "      rules (Category 33) determine whether the unused portion is refundable",
    "      and what penalty deduction applies. I use the same TRF → TRFT → TRFU → TRFP",
    "      workflow but the amount will reflect only the unused sectors.'",
  ],

  set_refund_tax_only: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'Can you refund taxes on a non-refundable ticket?'",
    "Say: 'Yes — even on non-refundable tickets, certain government taxes and airport",
    "      fees that are only collected when travel actually takes place may be",
    "      refundable if the passenger did not fly. I process this as a tax-only refund.",
    "      The fare itself is forfeited but the refundable taxes are returned.",
    "      I check which specific taxes are refundable in the ticket conditions",
    "      before processing through the TRF workflow.'",
  ],

  set_refund_atc: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is ATC Refund and how does it differ from a manual refund?'",
    "Say: 'ATC Refund automates the refund calculation using the airline-filed",
    "      Category 33 voluntary refund conditions stored in the system.",
    "      It calculates fare paid, used portion, cancellation penalty and refund amount",
    "      automatically. A manual refund requires the agent to calculate these manually",
    "      and enter the values. ATC Refund is faster and less error-prone,",
    "      but it is only available when Category 33 data exists for the fare.'",
  ],

  set_refund_involuntary: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How does an involuntary refund differ from a voluntary refund?'",
    "Say: 'A voluntary refund is processed when the passenger chooses not to travel.",
    "      Penalties from the fare rules apply and the refund amount may be partial.",
    "      An involuntary refund occurs when the airline cancels or significantly",
    "      changes the flight and the passenger declines the alternative.",
    "      In this case, the full fare and taxes are refundable — no penalty applies.",
    "      The process may require an airline waiver code or a specific involuntary",
    "      refund entry depending on the airline and BSP setup.'",
  ],

  set_fare_rules_basics: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'A passenger asks whether they can change their flight. How do you find out?'",
    "Say: 'I access the fare display with FQD for the route and fare basis, then",
    "      use FQN to read the fare rules — specifically Category 31 Voluntary Changes.",
    "      This tells me whether changes are permitted, the advance notice required,",
    "      and the penalty amount. If FQN is not available from the fare display,",
    "      I can also access fare notes from within the stored TST.'",
    "",
    "If asked: 'What are the most important fare rule categories to know for an interview?'",
    "Say: 'Category 31 — Voluntary Changes (penalties for date/flight changes).",
    "      Category 33 — Ticket Refunds (refund conditions and penalties).",
    "      Category 35 — Advance Purchase (how far in advance the ticket must be bought).",
    "      Category 5 — Advance Purchase. Category 6 — Minimum Stay. Category 7 — Maximum Stay.",
    "      These cover the most common passenger questions about flexibility.'",
  ],

  set_fare_rules_categories: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is Category PE in Amadeus fare rules?'",
    "Say: 'PE refers to Penalty conditions — it covers charges for voluntary changes",
    "      and cancellations. It is part of what is shown in Category 31 (Voluntary Changes)",
    "      and Category 33 (Refunds) in the standard IATA fare rule structure.",
    "      I read the PE conditions to tell a passenger exactly how much it will cost",
    "      to change or cancel their ticket.'",
    "",
    "If asked: 'What is VC in fare rules?'",
    "Say: 'VC stands for Voluntary Changes — conditions under which the passenger",
    "      may request itinerary modifications. It covers permitted change types,",
    "      advance notice requirements, and fee amounts.'",
  ],

  set_fare_rules_mini: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you quickly check key fare conditions without reading the full rules?'",
    "Say: 'I use FWR or FQF1 — the Mini Rules display — which gives a condensed",
    "      one-screen summary of the most important conditions: advance purchase,",
    "      minimum and maximum stay, stopovers, transfers, changes and refunds.",
    "      It is the fastest way to answer common passenger questions about",
    "      flexibility without reading through every category in full.'",
  ],

  set_pnr_retrieval_advanced: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'Describe every way you can retrieve a PNR in Amadeus.'",
    "Say: 'By record locator: RT ABC123.",
    "      By surname: RT/SMITH.",
    "      By surname and initial: RT/SMITH/J.",
    "      By surname and date: RT/12AUG-SMITH.",
    "      By flight, date and name: RT KL153/12AUG-SMITH.",
    "      By ticket number: RT TKT/016-1234567890.",
    "      From another system: RO [locator].",
    "      Purged PNR: RPD workflow.",
    "      If I get a list I select with RT1, RT2 etc. and RT0 returns to the list.",
    "      I can also retrieve using the TWD/TKT display and then RT*E to jump to the PNR.'",
  ],

  set_atc_voluntary_unflown: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'Walk me through ATC for a voluntary change on an unused ticket.'",
    "Say: 'I retrieve the PNR with RT and verify the ticket is OPEN with TWD.",
    "      I make the required itinerary change — for example rebooking to 28SEP with SB28SEP1.",
    "      I run FXF to get the informative ATC price — this shows the fare difference,",
    "      tax difference and any penalty. I tell the passenger the total due.",
    "      If they agree, I run FXQ to confirm the pricing and update the TST.",
    "      I check the TST with TQT, review the ATC reissue panel with TQR,",
    "      update the FOP if needed, end with ER, and issue the new ticket with TTP.",
    "      I verify the new ticket with TWD.'",
  ],

  set_atc_voluntary_partial: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'How do you handle ATC for a partially flown ticket?'",
    "Say: 'I display the ticket with TWD to identify which coupons are USED and which",
    "      are OPEN. I rebook the unflown sectors I need to change.",
    "      Critically, I must specify all unflown segments in the ATC entry —",
    "      for example FXF/S2-3 for segments 2 and 3. Without the segment selection",
    "      ATC cannot correctly calculate the reissue for the remaining journey.",
    "      Once the customer confirms, I run FXQ/S2-3 to update the TST.",
    "      I then check TQT and TQR, issue with TTP and verify with TWD.'",
    "",
    "If asked: 'What is the most common mistake on a partially flown ticket?'",
    "Say: 'Forgetting to include the /S... segment selection in the FXF and FXQ entries.",
    "      Without it, ATC either fails or prices the entire original itinerary",
    "      instead of just the remaining unflown sectors.'",
  ],

  set_atc_involuntary: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What does FXI do and how is it different from FXQ?'",
    "Say: 'FXI is the ATC Involuntary command — used when the airline has caused the",
    "      change. It automatically prepares the TST using the original fare, taxes,",
    "      FO from the original ticket, original FOP, and adds the endorsement FE SKCHG.",
    "      No additional collection or penalty is applied.",
    "      FXQ is for voluntary changes initiated by the passenger — it calculates",
    "      fare differences and penalties and requires a separate FXF informative step first.',",
    "      The rule: if the airline caused it, use FXI. If the passenger caused it, use FXQ.'",
  ],

  set_atc_best_pricer: [
    "",
    "--- INTERVIEW ANSWERS ---",
    "",
    "If asked: 'What is ATC Best Pricer?'",
    "Say: 'ATC Best Pricer is an enhanced version of standard ATC that searches for",
    "      a cheaper fare option for the new itinerary rather than simply applying",
    "      the same fare class. FXE is the Best Pricer informative command",
    "      (equivalent to FXF in standard ATC), and FXO confirms the Best Pricer",
    "      result (equivalent to FXQ). Use Best Pricer when the passenger wants",
    "      the most economical option for the new dates.'",
    "",
    "If asked: 'When would you use FXO instead of FXQ?'",
    "Say: 'When I have used FXE (Best Pricer informative) and the passenger agrees",
    "      to the best-price option, I confirm with FXO. If I used FXF (standard",
    "      informative) I confirm with FXQ. The pair must match:",
    "      FXF → FXQ, and FXE → FXO.'",
  ],
};

// Apply
let updatedCount = 0;
sets = sets.map(set => {
  if (deepQA[set.id]) {
    if (!set.questions) set.questions = [];
    set.questions = set.questions.concat(deepQA[set.id]);
    updatedCount++;
  }
  return set;
});

const newCode = 'const guidedSets = ' + JSON.stringify(sets, null, 2) + ';\n\nmodule.exports = guidedSets;\n';
fs.writeFileSync('generateGuidedSets.cjs', newCode);
console.log(`Deep interview Q&As added to ${updatedCount} sets.`);
